pubmed:
  M_nodes: 64
  adaptive: False
  add_source: True
  adjoint: True
  adjoint_method: adaptive_heun
  adjoint_step_size: 1
  alpha: 1.0
  alpha_dim: sc
  att_samp_pct: 1
  attention_dim: 16
  attention_norm_idx: 1
  attention_rewiring: False
  attention_type: cosine_sim
  augment: False
  baseline: False
  batch_norm: False
  beltrami: True
  beta_dim: sc
  block: attention
  cpus: 1
  data_norm: rw
  dataset: Pubmed
  decay: 0.0018236722171703636
  directional_penalty: None
  dropout: 0.07191100715473969
  dt: 0.001
  dt_min: 1.0e-05
  epoch: 50
  exact: False
  fc_out: False
  feat_hidden_dim: 250  # 64
  function: laplacian
  gdc_avg_degree: 64
  gdc_k: 64
  gdc_method: ppr
  gdc_sparsification: topk
  gdc_threshold: 0.01
  gpus: 1.0
  grace_period: 20
  heads: 1
  heat_time: 3.0
  hidden_dim: 500
  input_dropout: 0.5
  jacobian_norm2: None
  kinetic_energy: None
  label_rate: 0.5
  leaky_relu_slope: 0.2
  lr: 0.014669345840305131
  max_epochs: 1000
  max_iters: 100
  max_nfe: 5000
  method: dopri5
  metric: MRR
  mix_features: False
  name: None
  new_edges: random
  no_alpha_sigmoid: False
  not_lcc: True
  num_init: 1
  num_samples: 400
  num_splits: 8
  ode_blocks: 1
  optimizer: adamax
  patience: 100
  pos_enc_dim: row
  pos_enc_hidden_dim: 250  # 16
  ppr_alpha: 0.05
  reduction_factor: 10
  regularise: False
  reweight_attention: False
  rewire_KNN: False
  rewire_KNN_T: T0
  rewire_KNN_epoch: 10
  rewire_KNN_k: 64
  rewire_KNN_sym: False
  rewiring: None
  rw_addD: 0.02
  rw_rmvR: 0.02
  self_loop_weight: 1
  sparsify: S_hat
  square_plus: True
  step_size: 1
  threshold_type: addD_rvR
  time: 12.942327880200853
  tol_scale: 1991.0688305523001
  tol_scale_adjoint: 16324.368093998313
  total_deriv: None
  use_cora_defaults: False
  use_flux: False
  use_labels: False
  use_lcc: True
  use_mlp: False
  folder: pubmed_linear_att_beltrami_adj2
  index: 0
  run_with_KNN: False
  change_att_sim_type: False
  reps: 1
  max_test_steps: 100
  no_early: True  # False
  earlystopxT: 5.0
  pos_enc_csv: False
  pos_enc_type: DW500

  # Additional hyperparameters
  batch_size: 256
  dataset_dir: ./dataset
  fa_layer: false
  gcn: true
  mlp_num_layers: 3
  no_early: true
  use_valedges_as_input: false